/**
 * @fileoverview ChatFormatter.js - Client-Side Chat Text & Timestamp Formatting Utilities
 * 
 * @description
 * Architectural role: Static presentation helper for the TastyTails client chat system.
 * Triggered by: ChatMessage rendering loop during WebSocket message broadcasts and history hydration.
 * 
 * Features:
 * - High-throughput date formatting using a pre-allocated Intl.DateTimeFormat instance.
 * - Input validation & fallback logic to prevent UI rendering bugs on invalid date payloads.
 * - Safe HTML entity escaping for plain-text UI rendering.
 */
class ChatFormatter {
    /**
     * OPTIMIZATION: Reusable Intl.DateTimeFormat static instance.
     * Pre-instantiating avoids per-message object allocations ({ hour, minute }) and V8 locale resolution overhead.
     * Uses 'undefined' locale parameter to dynamically inherit browser default locale safely across runtimes.
     * @private
     */
    static _timeFormatter = new Intl.DateTimeFormat(undefined, { hour: '2-digit', minute: '2-digit' });

    /**
     * Formats an ISO 8601 date string or numeric epoch timestamp into a localized time string (HH:MM AM/PM).
     * 
     * @param {string|number} dateString - ISO 8601 Date String or numeric timestamp
     * @returns {string} Formatted localized time string (e.g., "02:45 PM") or "" if input is invalid/empty
     */
    static formatTime(dateString) {
        if (!dateString) return '';
        
        // Handle numeric epoch timestamps or parse ISO date string
        const timestamp = typeof dateString === 'number' ? dateString : Date.parse(dateString);
        
        // Defensive check: guard against NaN to prevent rendering "Invalid Date" in UI bubbles
        if (isNaN(timestamp)) return '';
        
        return this._timeFormatter.format(new Date(timestamp));
    }

    /**
     * Escapes plain-text inputs for safe DOM insertion to prevent XSS.
     * 
     * @warning Do NOT invoke this on server-sanitized Markdown/HTML content generated by MessageSystem.js,
     * as double-escaping will break rich formatting (bold, italics, spoilers, image tags).
     * 
     * @param {string} text - Raw plain-text string
     * @returns {string} HTML-escaped safe string
     */
    static sanitize(text) {
        if (typeof text !== 'string') return text || '';
        return text
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    }
}

// Register on global window object for non-bundled script tag compatibility in play.ejs
window.ChatFormatter = ChatFormatter;
