/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/craftingStations.js
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */

/**
 * @fileoverview craftingStations.js - Authoritative Crafting Station Registry
 * 
 * @description
 * Defines UI titles, button labels, FontAwesome icon defaults, slot capacities,
 * and CSS themes for all crafting station types across TastyTails.net.
 * 
 * Invoked by:
 * - src/server-loop.js (Station slot limits & client payload construction)
 * - src/sockets/craftingHandlers.js (Server-side input validation & socket payload)
 * - src/client/js/game/crafting.js (Dynamic UI modal rendering & CSS skinning)
 */

/**
 * @typedef {Object} StationModuleConfig
 * @property {boolean} [recipeList] - Toggles visibility of the left-hand recipe selection list sidebar.
 * @property {boolean} [craftingInfo] - Toggles visibility of the recipe preview & requirement info panel.
 * @property {string} [type] - Custom module renderer identifier (e.g. 'sewing_custom').
 */

/**
 * @typedef {Object} CraftingStationConfig
 * @property {string} title - Window header title string.
 * @property {string} recipeBookTitle - Recipe sidebar header title string.
 * @property {string} recipeSelectPrompt - Placeholder instruction prompt text.
 * @property {string} inputLabel - Header label for the input crucible container.
 * @property {string} outputLabel - Header label for the output cooling rack container.
 * @property {string} buttonLabel - Primary action button text.
 * @property {string} actionProgressLabel - Status label shown during active crafting progress.
 * @property {string} defaultRecipeIcon - FontAwesome icon class fallback.
 * @property {number} inputSlots - Maximum allowed input inventory slots (validated on server).
 * @property {string} theme - Root CSS theme class name (e.g. 'theme-forge').
 * @property {StationModuleConfig} modules - Structural UI module flags.
 */

// OPTIMIZATION: Object.freeze guarantees runtime immutability and prevents accidental global state pollution across player sockets.
/** @type {Object.<string, CraftingStationConfig>} */
const craftingStations = Object.freeze({

    anvil: {
        title: "The Hearthside Forge",
        texture: "anvil_01",
        recipeBookTitle: "Blueprints",
        recipeSelectPrompt: "Select a Blueprint",
        inputLabel: "Crucible (Deposit Materials)",
        outputLabel: "Cooling Rack",
        buttonLabel: "Strike Iron",
        actionProgressLabel: "Forging...",
        defaultRecipeIcon: "fa-scroll",
        inputSlots: 6,
        theme: "theme-forge",
        layoutType: "standard",
        interactionVerb: "Forge",
        modules: {
            recipeList: true,
            craftingInfo: true
        }
    },
    furnace: {
        title: "Smelter",
        texture: "smelter",
        recipeBookTitle: "Smelting Recipes",
        recipeSelectPrompt: "Select Ore",
        inputLabel: "Fuel & Ore Input",
        outputLabel: "Output Tray",
        buttonLabel: "Ignite",
        actionProgressLabel: "Smelting...",
        defaultRecipeIcon: "fa-fire",
        inputSlots: 3,
        theme: "theme-smelter",
        layoutType: "single_input",
        interactionVerb: "Smelt",
        autoMatch: true,
        modules: {
            recipeList: false,
            craftingInfo: true
        }
    },
    cocktail_bar: {
        title: "The Tipsy Tail",
        texture: "cocktail_bar",
        recipeBookTitle: "Menu",
        recipeSelectPrompt: "Select a Drink",
        inputLabel: "Mixing Glass",
        outputLabel: "Serving Counter",
        buttonLabel: "Mix Drink",
        actionProgressLabel: "Mixing...",
        defaultRecipeIcon: "fa-cocktail",
        inputSlots: 4,
        theme: "theme-cocktail",
        layoutType: "standard",
        interactionVerb: "Mix",
        modules: {
            recipeList: true,
            craftingInfo: true
        }
    },
    juicer: {
        title: "Juicer",
        texture: "juicer",
        recipeBookTitle: "Juicing Recipes",
        recipeSelectPrompt: "Select a Fruit",
        inputLabel: "Fruit Input",
        outputLabel: "Output Tray",
        buttonLabel: "Juice",
        actionProgressLabel: "Juicing...",
        defaultRecipeIcon: "fa-cocktail",
        inputSlots: 1,
        theme: "theme-juicer",
        layoutType: "single_input",
        interactionVerb: "Juice",
        autoMatch: true,
        modules: {
            recipeList: false,
            craftingInfo: true
        }
    },
    distillery: {
        title: "Distillery",
        texture: "distillery",
        recipeBookTitle: "Distilling Recipes",
        recipeSelectPrompt: "Select a Fruit",
        inputLabel: "Fruit Input",
        outputLabel: "Output Tray",
        buttonLabel: "Distill",
        actionProgressLabel: "Distilling...",
        defaultRecipeIcon: "fa-cocktail",
        inputSlots: 1,
        theme: "theme-distillery",
        layoutType: "single_input",
        interactionVerb: "Distill",
        autoMatch: true,
        modules: {
            recipeList: false,
            craftingInfo: true
        }
    },
    spinning_wheel: {
        title: "Spinning Wheel",
        texture: "spinning_wheel",
        recipeBookTitle: "Spinning Recipes",
        recipeSelectPrompt: "Deposit Fiber & Dye",
        inputLabel: "Fiber & Dye Input",
        outputLabel: "Spool Rack",
        buttonLabel: "Spin Thread",
        actionProgressLabel: "Spinning Thread...",
        defaultRecipeIcon: "fa-solid fa-scroll",
        inputSlots: 2,
        theme: "theme-spinner",
        layoutType: "single_input",
        interactionVerb: "Spin",
        autoMatch: true,
        modules: {
            recipeList: false,
            craftingInfo: true
        }
    },
    sewing_machine: {
        title: "Sewing Machine",
        texture: "sewing_machine",
        recipeBookTitle: "Sewing Recipes",
        recipeSelectPrompt: "Select a Fiber",
        inputLabel: "Fiber Input",
        outputLabel: "Output Tray",
        buttonLabel: "Sew",
        actionProgressLabel: "Sewing...",
        defaultRecipeIcon: "fa-cocktail",
        inputSlots: 4,
        theme: "theme-seamstress",
        layoutType: "pattern_grid",
        interactionVerb: "Sew",
        modules: {
            recipeList: false,
            craftingInfo: false,
            type: 'sewing_custom'
        }
    },
    cauldron: {
        title: "Cauldron",
        texture: "cauldron",
        recipeBookTitle: "Cauldron Recipes",
        recipeSelectPrompt: "Select an Ingredient",
        inputLabel: "Ingredient Input",
        outputLabel: "Output Tray",
        buttonLabel: "Brew",
        actionProgressLabel: "Brewing...",
        defaultRecipeIcon: "fa-cocktail",
        inputSlots: 1,
        theme: "theme-alchemy",
        layoutType: "standard",
        interactionVerb: "Brew",
        modules: {
            recipeList: true,
            craftingInfo: true
        }
    },
    alembic: {
        title: "The Alchemist's Alembic",
        texture: "alembic",
        recipeBookTitle: "Distillation Recipes",
        recipeSelectPrompt: "Select Ingredients & Adjust Ratio",
        inputLabel: "Distillate Ingredients (2 Slots)",
        outputLabel: "Distillate Receiver",
        buttonLabel: "Blend & Distill",
        actionProgressLabel: "Distilling...",
        defaultRecipeIcon: "fa-solid fa-vial",
        inputSlots: 2,
        theme: "theme-alembic",
        layoutType: "stepper_ratio",
        interactionVerb: "Distill",
        modules: {
            recipeList: false,
            craftingInfo: false,
            type: 'alembic_custom'
        }
    },
});

export default Object.freeze(craftingStations);
