/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/itemData.js
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */

/**
 * itemData.js (ONLY EDIT THIS FILE WHEN CREATING OR CHANGING ITEMS)
 * Definitions for items, specifically their physical size.
 * Defaults to size 1 if not found.
 */
export default {
    // Basic Items
    'glass_beer': { size: 1, name: 'Beer Glass', icon: 'fa-glass-whiskey', texture: 'glass_beer' },
    'bottle_empty': { size: 1, name: 'Empty Bottle', icon: 'fa-wine-bottle', texture: 'bottle_empty', description: 'An empty glass bottle.' },
    'key': { size: 1, name: 'Key', icon: 'fa-key', texture: 'key' },
    'scroll_01': { size: 1, name: 'Test Scroll', icon: 'fa-scroll', texture: 'scroll2', description: 'A testing scroll.' },

    // Drink Bottles
    'bottle_ale': { size: 1, name: 'Ale Bottle', icon: 'fa-glass-whiskey', texture: 'bottle_ale', playerUse: true, returnOnEmpty: 'bottle_empty' },
    'bottle_wine': { size: 1, name: 'Wine Bottle', icon: 'fa-glass-whiskey', texture: 'bottle_wine', playerUse: true, returnOnEmpty: 'bottle_empty' },
    'bottle_whiskey': { size: 1, name: 'Whiskey Bottle', icon: 'fa-glass-whiskey', texture: 'bottle_whiskey', playerUse: true, returnOnEmpty: 'bottle_empty' },
    'bottle_beer': { size: 1, name: 'Beer Bottle', icon: 'fa-glass-whiskey', texture: 'bottle_beer', playerUse: true, returnOnEmpty: 'bottle_empty' },

    // Tools/Weapons
    'stick': { size: 4, name: 'Sturdy Stick' },
    'sword': { size: 10, name: 'Iron Sword' },

    // Crafting Items
    'ore_iron': { size: 2, name: 'Iron Ore', icon: 'fa-gem', texture: 'ore_iron', flavor: `Hard and metallic`, description: `A chunk of iron ore.`, verb: 'use', maxUses: 1, playerUse: false },
    'ingot_iron': { size: 2, name: 'Iron Ingot', icon: 'fa-cube', texture: 'ingot_iron', flavor: `Hard and metallic`, description: `An ingot of iron.`, verb: 'use', maxUses: 1, playerUse: false },

    // Default
    'default': { size: 1, name: 'Unknown Object' },

    // Food
    'food_orange': { size: 1, name: 'Orange', icon: 'fa-apple-whole', texture: 'food_orange', flavor: `Tangy and sweet`, description: `A juicy orange.`, verb: 'eat', maxUses: 1, playerUse: true, isDynamic: true },
    'food_potato': { size: 1, name: 'Potato', icon: 'fa-apple-whole', texture: 'food_potato', flavor: `Starchy and savory`, description: `A rich potato.`, verb: 'eat', maxUses: 1, playerUse: true, isDynamic: true },

    // Tools
    'tool_sheers': { size: 1, name: 'Sheers', icon: 'fa-apple-whole', texture: 'sheers', flavor: `Tastes like metal`, description: `Big heavy scissors`, verb: 'use', maxUses: 1, playerUse: false },

    // Fibers
    'fiber_wool': { size: 1, name: 'Wool Fiber', icon: 'fa-apple-whole', texture: 'fiber_wool', flavor: `Soft and warm`, description: `A roll of wool fiber.`, verb: 'use', maxUses: 1, playerUse: false },

    // Dye precursors
    'indigo': { size: 1, name: 'Indigo', icon: 'fa-apple-whole', texture: 'indigo', flavor: `Pungent`, description: `A roll of indigo fiber.`, verb: 'use', maxUses: 1, playerUse: false },
    'madder_root': { size: 1, name: 'Madder Root', icon: 'fa-apple-whole', texture: 'madder_root', flavor: `Pungent`, description: `A roll of madder root fiber.`, verb: 'use', maxUses: 1, playerUse: false },
    'weld': { size: 1, name: 'Weld', icon: 'fa-apple-whole', texture: 'weld', flavor: `Pungent`, description: `A roll of weld fiber.`, verb: 'use', maxUses: 1, playerUse: false },


    // Special
    'alpha_bottle': {
        size: 3,
        name: 'Alpha Bottle',
        icon: 'fa-tint',
        texture: 'alpha_bottle',
        maxUses: 9,
        playerUse: true,
        returnOnEmpty: 'bottle_empty',
        isDynamic: true,
        color: 0x66ccff,
        verb: 'Drink',
        flavor: 'A bubbling blue liquid.',
        description: 'A strange bottle that seems to refill itself.',
        rendering: {
            type: 'layered',
            layers: [
                { frameOffset: 10, tintParam: 'color' }, // Liquid (Bottom)
                { frameOffset: 0, interactive: true }    // Bottle (Top)
            ]
        }
    },
    'alpha_dye': {
        size: 1,
        name: 'Alpha Dye',
        icon: 'fa-tint',
        texture: 'alpha_dye',
        maxUses: 10,
        playerUse: false,
        isDynamic: true,
        color: 0xFFC0CB,
        verb: 'use',
        flavor: 'pungent',
        description: 'A bottle of dye',
        rendering: {
            type: 'layered',
            layers: [
                { frameOffset: 10, tintParam: 'color' }, // Liquid (Bottom)
                { frameOffset: 0, interactive: true }    // Bottle (Top)
            ]
        }
    },
    'alpha_thread': {
        size: 1,
        name: 'Alpha Thread',
        icon: 'fa-tint',
        texture: 'alpha_thread',
        maxUses: 10,
        playerUse: false,
        isDynamic: true,
        color: 0xFFFFFF,
        verb: 'unspool',
        flavor: 'cloth',
        description: 'A roll of thread',
        rendering: {
            type: 'layered',
            layers: [
                { frameOffset: 0 }, // spool (Bottom)
                { frameOffset: 10, tintParam: 'color', interactive: true } // thread (Top)
            ]
        }
    },
    'shirt_01': {
        name: 'Plain T-Shirt',
        equipSlot: 'torsoOuter',
        isItem: true,
        itemId: 'shirt_01',
        itemType: 'clothing',
        texture: 'shirt_01',
        icon: 'fa-shirt', // Changed to fa-shirt to match context
        maxUses: 1,
        playerUse: false,
        isDynamic: true,
        color: 0xFFFFFF,
        verb: 'wear',
        flavor: 'cloth',
        description: 'A simple plain t-shirt.',
        pockets: [
            { id: 'breast_pocket', name: 'Front Pocket', capacity: 2 }
        ]
    }
};

