/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/resourceNodeData.js
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */

/**
 * @fileoverview Centralized Static Resource Node Registry (`resourceNodeData.js`)
 * 
 * @description
 * Primary single source of truth for interactive environment objects (trees, rocks, agricultural crops).
 * Shared across the server loop (physics body collision, distance checks, harvest mechanics, regrowth timers)
 * and the client engine (spritesheet preloading, map collision offset calculation, layered crop rendering).
 * 
 * @typedef {Object} ResourceNodeDefinition
 * @property {string} name - Human-readable display name.
 * @property {string} description - Flavor text description for examine UI.
 * @property {number} [frameWidth] - Spritesheet tile width for Phaser asset preloader.
 * @property {number} [frameHeight] - Spritesheet tile height for Phaser asset preloader.
 * @property {number} [bodyWidth] - Phaser arcade physics body collision width.
 * @property {number} [bodyHeight] - Phaser arcade physics body collision height.
 * @property {number} [bodyOffsetY] - Vertical offset to align physics body with base of sprite.
 * @property {string} interactType - Interaction action identifier ('gather', 'mine', 'chop').
 * @property {string} gatherItem - Inventory item ID awarded upon harvesting.
 * @property {string} [gatherSeed] - Optional seed item ID dropped during harvest.
 * @property {string} gatherTool - Required tool item ID ('tool_pickaxe', 'none').
 * @property {number} maxCapacity - Maximum harvest capacity before node is depleted.
 * @property {number} regrowTime - Regrowth interval in seconds per capacity unit.
 * @property {boolean} [regrowable=true] - OPTIMIZATION: Set false for single-use crops to bypass server tick timer loops.
 * @property {boolean} [skipPreload=false] - OPTIMIZATION: Set true for layered nodes to avoid non-existent tilemap 404s in preloader.
 * @property {Object.<number, number>} capacityFrames - Map of remaining capacity to spritesheet frame index.
 * @property {boolean} [preventPickup] - Prevents object from being picked up directly into inventory.
 * @property {boolean} [isGround] - Indicates object rests flat on the ground plane.
 * @property {boolean} [gatherable] - Enables gather interaction flag.
 * @property {Object} [rendering] - Composite layer rendering rules (e.g. soil + crop sprite).
 */

export default Object.freeze({
    // =========================================================================
    // TREES & NATURAL HARVESTABLE NODES
    // =========================================================================
    'tree_orange': {
        name: 'Orange Tree',
        description: 'A vibrant orange tree heavy with ripe fruit.',
        frameWidth: 230,
        frameHeight: 291,
        bodyWidth: 30,
        bodyHeight: 15,
        bodyOffsetY: 5,
        interactType: 'gather',
        gatherItem: 'food_orange',
        gatherTool: 'none',
        maxCapacity: 5,
        regrowTime: 60, // Regrows 1 capacity every 60 seconds
        capacityFrames: {
            5: 0,
            4: 1,
            3: 2,
            2: 3,
            1: 4,
            0: 5
        }
    },
    'rock_iron': {
        name: 'Iron Rock',
        description: 'A rock containing iron ore.',
        frameWidth: 64,
        frameHeight: 64,
        bodyWidth: 64,
        bodyHeight: 15,
        bodyOffsetY: 5,
        interactType: 'gather',
        gatherItem: 'ore_iron',
        gatherTool: 'tool_pickaxe', // Enforced by interactionHandlers.js and server-loop.js
        maxCapacity: 5,
        regrowTime: 60, // Regrows 1 capacity every 60 seconds
        capacityFrames: {
            5: 0,
            4: 1,
            3: 2,
            2: 3,
            1: 4,
            0: 5
        }
    },

    // =========================================================================
    // AGRICULTURAL CROPS (Layered rendering, non-regrowable single harvest)
    // =========================================================================
    'plant_indigo_node': {
        name: 'Indigo Plant',
        description: 'A mature indigo plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'indigo',
        gatherSeed: 'seed_indigo',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        // OPTIMIZATION: Bypasses server tick loop and skips non-existent preloader tilemaps
        regrowable: false,
        skipPreload: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_indigo' }
            ]
        }
    },
    'plant_madder_root_node': {
        name: 'Madder Root Plant',
        description: 'A mature madder root plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'madder_root',
        gatherSeed: 'seed_madder_root',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        // OPTIMIZATION: Bypasses server tick loop and skips non-existent preloader tilemaps
        regrowable: false,
        skipPreload: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_madder_root' }
            ]
        }
    },
    'plant_weld_node': {
        name: 'Weld Plant',
        description: 'A mature weld plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'weld',
        gatherSeed: 'seed_weld',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        // OPTIMIZATION: Bypasses server tick loop and skips non-existent preloader tilemaps
        regrowable: false,
        skipPreload: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_weld' }
            ]
        }
    },
    'plant_potato_node': {
        name: 'Potato Plant',
        description: 'A mature potato plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'food_potato',
        gatherSeed: 'seed_potato',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        // OPTIMIZATION: Bypasses server tick loop and skips non-existent preloader tilemaps
        regrowable: false,
        skipPreload: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_potato' }
            ]
        }
    },

    // =========================================================================
    // WILD VEGETATION & FLORA (Dynamic plantZone Ecological Nodes)
    // =========================================================================
    'flora_tall_grass': {
        name: 'Wild Tall Grass',
        description: 'Lush, fibrous meadow grass favored by grazing woodland animals.',
        interactType: 'gather',
        gatherItem: 'fiber_plant',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999, // Managed by EcologyManager relocation respawn
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true
    },
    'flora_clover': {
        name: 'White Clover Patch',
        description: 'A cluster of sweet clover blossoms rich in nutrients.',
        interactType: 'gather',
        gatherItem: 'clover_leaf',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true
    },
    'flora_dandelion': {
        name: 'Yellow Dandelion',
        description: 'A bright yellow bloom edible by herbivores and prized for yellow pigments.',
        interactType: 'gather',
        gatherItem: 'flower_dandelion',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true
    },
    'flora_flower_1': {
        name: 'Red Poppy',
        description: 'A delicate crimson wildflower containing vibrant red dye pigments.',
        interactType: 'gather',
        gatherItem: 'petal_red',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true
    },
    'flora_flower_2': {
        name: 'Blue Starflower',
        description: 'A rare indigo-blue wildflower that flourishes in shaded clearings.',
        interactType: 'gather',
        gatherItem: 'petal_blue',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true
    },
    'flora_flower_3': {
        name: 'Yellow Marigold',
        description: 'A sunny golden marigold known for sweet nectar and herbal remedies.',
        interactType: 'gather',
        gatherItem: 'petal_yellow',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true
    },
    'flora_berry_bush': {
        name: 'Sweet Berry Bush',
        description: 'A hardy woodland bush laden with ripe, sweet wild berries.',
        interactType: 'gather',
        gatherItem: 'food_berry',
        gatherTool: 'none',
        maxCapacity: 2,
        regrowTime: 999999,
        regrowable: false,
        isDynamicFlora: true,
        capacityFrames: { 2: 0, 1: 0, 0: 0 },
        preventPickup: true,
        isGround: false,
        gatherable: true
    }
});
