/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/resourceNodeData.js
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */

/**
 * resourceNodeData.js
 * Source of truth for interactive environment objects (trees, rocks, plants, etc.).
 * Shared by server (physics/state) and client (preloading/visuals).
 */
export default {
    'tree_orange': {
        name: 'Orange Tree',
        description: 'A vibrant orange tree heavy with ripe fruit.',
        frameWidth: 230,
        frameHeight: 291,
        bodyWidth: 30,
        bodyHeight: 15,
        bodyOffsetY: 5,
        interactType: 'gather',
        gatherItem: 'food_orange',
        gatherTool: 'none',
        maxCapacity: 5,
        regrowTime: 60, // Regrows 1 capacity every 60 seconds
        capacityFrames: {
            5: 0,
            4: 1,
            3: 2,
            2: 3,
            1: 4,
            0: 5
        }
    },
    'rock_iron': {
        name: 'Iron Rock',
        description: 'A rock containing iron ore.',
        frameWidth: 64,
        frameHeight: 64,
        bodyWidth: 64,
        bodyHeight: 15,
        bodyOffsetY: 5,
        interactType: 'gather',
        gatherItem: 'ore_iron',
        gatherTool: 'tool_pickaxe',
        maxCapacity: 5,
        regrowTime: 60, // Regrows 1 capacity every 60 seconds
        capacityFrames: {
            5: 0,
            4: 1,
            3: 2,
            2: 3,
            1: 4,
            0: 5
        }
    },
    'plant_indigo_node': {
        name: 'Indigo Plant',
        description: 'A mature indigo plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'indigo',
        gatherSeed: 'seed_indigo',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_indigo' }
            ]
        }
    },
    'plant_madder_root_node': {
        name: 'Madder Root Plant',
        description: 'A mature madder root plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'madder_root',
        gatherSeed: 'seed_madder_root',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_madder_root' }
            ]
        }
    },
    'plant_weld_node': {
        name: 'Weld Plant',
        description: 'A mature weld plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'weld',
        gatherSeed: 'seed_weld',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_weld' }
            ]
        }
    },
    'plant_potato_node': {
        name: 'Potato Plant',
        description: 'A mature potato plant ready for harvest.',
        interactType: 'gather',
        gatherItem: 'food_potato',
        gatherSeed: 'seed_potato',
        gatherTool: 'none',
        maxCapacity: 1,
        regrowTime: 999999,
        capacityFrames: { 1: 0, 0: 0 },
        preventPickup: true,
        isGround: true,
        gatherable: true,
        rendering: {
            type: 'layered',
            layers: [
                { texture: 'tilled_soil_planted' },
                { texture: 'plant_potato' }
            ]
        }
    }
};
