const fs = require('fs');
const path = require('path');

const sourcePath = path.join(__dirname, '../src/data/itemData.js');
const destPath = path.join(__dirname, '../src/client/js/game/itemData.js');

try {
    console.log('[Sync] Reading item data from:', sourcePath);
    let content = fs.readFileSync(sourcePath, 'utf8');

    // Convert CommonJS to ES Module
    // Replace "module.exports =" with "export default"
    // We utilize a flexible regex to catch variations in spacing
    content = content.replace(/module\.exports\s*=\s*/, 'export default ');

    // Add Auto-Generation Header
    const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/itemData.js
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */\n\n`;

    const finalContent = header + content;

    console.log('[Sync] Writing item data to:', destPath);
    fs.writeFileSync(destPath, finalContent, 'utf8');
    console.log('[Sync] Synchronization complete.');

} catch (err) {
    console.error('[Sync] Error synchronizing item data:', err);
    process.exit(1);
}
