const fs = require('fs');
const path = require('path');

const filesToSync = [
    {
        source: '../src/data/itemData.js',
        dest: '../src/client/js/game/itemData.js',
        name: 'itemData.js'
    },
    {
        source: '../src/data/resourceNodeData.js',
        dest: '../src/client/js/game/resourceNodeData.js',
        name: 'resourceNodeData.js'
    }
];

filesToSync.forEach(file => {
    const sourcePath = path.join(__dirname, file.source);
    const destPath = path.join(__dirname, file.dest);

    try {
        console.log(`[Sync] Reading ${file.name} from:`, sourcePath);
        let content = fs.readFileSync(sourcePath, 'utf8');

        // Convert CommonJS to ES Module
        content = content.replace(/module\.exports\s*=\s*/, 'export default ');

        // Add Auto-Generation Header
        const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/${file.name}
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */\n\n`;

        const finalContent = header + content;

        console.log(`[Sync] Writing ${file.name} to:`, destPath);
        fs.writeFileSync(destPath, finalContent, 'utf8');
        console.log(`[Sync] Synchronization of ${file.name} complete.`);

    } catch (err) {
        console.error(`[Sync] Error synchronizing ${file.name}:`, err);
        process.exit(1);
    }
});
