const fs = require('fs');
const path = require('path');

const filesToSync = [
    {
        source: '../src/data/itemData.js',
        dest: '../src/client/js/game/itemData.js',
        name: 'itemData.js'
    },
    {
        source: '../src/data/resourceNodeData.js',
        dest: '../src/client/js/game/resourceNodeData.js',
        name: 'resourceNodeData.js'
    }
];

function safeWriteFileSync(targetPath, data) {
    const maxRetries = 5;
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            // Remove existing file if locked or read-only before overwrite
            if (attempt > 1 && fs.existsSync(targetPath)) {
                try { fs.chmodSync(targetPath, 0o666); } catch (e) {}
            }
            fs.writeFileSync(targetPath, data, 'utf8');
            return;
        } catch (err) {
            if (attempt === maxRetries) throw err;
            const start = Date.now();
            while (Date.now() - start < 150) {} // Wait 150ms before retry
        }
    }
}

filesToSync.forEach(file => {
    const sourcePath = path.join(__dirname, file.source);
    const destPath = path.join(__dirname, file.dest);

    try {
        console.log(`[Sync] Reading ${file.name} from:`, sourcePath);
        let content = fs.readFileSync(sourcePath, 'utf8');

        // Convert CommonJS to ES Module with Object.freeze
        content = content.replace(/module\.exports\s*=\s*/, 'export default Object.freeze(');
        content = content.trim().replace(/;?$/, ');\n');

        // Add Auto-Generation Header
        const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Source: src/data/${file.name}
 * Generated by: scripts/sync-items.js
 * 
 * Edit the source file instead.
 */\n\n`;

        const finalContent = header + content;

        console.log(`[Sync] Writing ${file.name} to:`, destPath);
        safeWriteFileSync(destPath, finalContent);
        console.log(`[Sync] Synchronization of ${file.name} complete.`);

    } catch (err) {
        console.error(`[Sync] Error synchronizing ${file.name}:`, err);
        process.exit(1);
    }
});
