// =========================================================================================================
// CRITICAL: DO NOT MODIFY, TRUNCATE, OR SUMMARIZE THE TEXT AND DESCRIPTIONS IN THIS ARRAY WITHOUT
// EXPLICIT USER INSTRUCTIONS. THE EXACT STRINGS AND DESCRIPTIONS IN THIS ARRAY MUST BE PRESERVED.
// =========================================================================================================
window.voreList = [
    { id: 1, graphNodeId: "1", type: "entrance", destination: "Maw", verb: "shoves", x: 25, y: 100, protoConnections: [3], destinationDescrip: "You are pulled between <pred>'s lips...", examineMsgDescrip: "<pred>'s cheeks are swollen with <prey>...", struggleInsideMsgDescrip: "You pry at the jaws...", struggleOutsideMsgDescrip: "<pred>'s cheeks puff out..." },
    { id: 2, graphNodeId: "2", type: "entrance", destination: "Anus", verb: "squelches", x: 25, y: 240, protoConnections: [4], destinationDescrip: "You can feel the slimy walls of <pred>'s anal canal rippling around you...", examineMsgDescrip: "<prey> is slowly being worked up into <pred>'s tight ass...", struggleInsideMsgDescrip: "You push against the tight ring...", struggleOutsideMsgDescrip: "<pred> groans as their ass tightens around the intruding prey..." },
    { id: 3, graphNodeId: "3", type: "path", destination: "Gullet", x: 165, y: 100, protoConnections: [5], destinationDescrip: "The tight tube squeezes you down...", examineMsgDescrip: "A bulge is working it's way down <pred>'s throat...", struggleInsideMsgDescrip: "The walls constrict tightly...", struggleOutsideMsgDescrip: "A bulge travels down <pred>'s throat..." },
    { id: 4, graphNodeId: "4", type: "path", destination: "Bowels", x: 165, y: 240, protoConnections: [5], destinationDescrip: "You feel the musky walls of <pred>'s digestive tract undulating around you as you are shoved up their ass.", examineMsgDescrip: "<pred>'s lower abdomen seems to be swollen out quite a lot...did something just move?", struggleInsideMsgDescrip: "Wriggling about only seems to make that tight fleshy tube squeeze tighter around your body.", struggleOutsideMsgDescrip: "The outline of a footprint forms against the surface of <pred>'s lower belly" },
    { id: 5, graphNodeId: "5", type: "destination", destination: "Stomach", digestionTimer: "120", x: 305, y: 100, protoConnections: [6], destinationDescrip: "TThe walls feel hot and slimy as they constrict around you.", examineMsgDescrip: "<pred>'s belly looks as though something inside is moving...", struggleInsideMsgDescrip: "Pressing against the slimy walls doesn't seem to get much of a reaction from <pred>.", struggleOutsideMsgDescrip: "<pred>'s belly bulges out with the outline of a hand print for a moment before returning to it's distended shape.", digestionInsideMsgDescrip: "The constant liquid churning inside<pred>'s stomach causes your form to contort and squirm uncomfortably until you can no longer recognize your own shape and your mind melts away into nothingness.", digestionOutsideMsgDescrip: "The constant movement inside <pred>'s middle finally goes still as a soft gurgling sound comes from their belly.", releaseMsgDescrip: "<pred> leans forward and heaves, forcing you back out into the light." },
    { id: 6, graphNodeId: "6", type: "exit", destination: "Anus", x: 445, y: 100, destinationDescrip: "You are squeezed into the lower intestines...", examineMsgDescrip: "<pred>'s anus bulges outward...", struggleInsideMsgDescrip: "There is little room to move...", struggleOutsideMsgDescrip: "<pred>'s lower belly churns..." },
    { id: 7, graphNodeId: "7", type: "entrance", destination: "Slit", verb: "presses", x: 25, y: 380, protoConnections: [8], destinationDescrip: "You are pulled past <pred>'s soft outer lips...", examineMsgDescrip: "<pred> is working <prey> in and out of their pussy...", struggleInsideMsgDescrip: "You struggle against the slick folds...", struggleOutsideMsgDescrip: "<pred>'s hips twitch as <prey> pushes from inside..." },
    { id: 8, graphNodeId: "8", type: "path", destination: "Canal", x: 165, y: 380, protoConnections: [9], destinationDescrip: "The tight, ribbed canal squeezes tightly around you...", examineMsgDescrip: "<pred>'s lower tummy is distended with the shape of <prey> sliding in deeper...", struggleInsideMsgDescrip: "The fleshy passage grips you firmly...", struggleOutsideMsgDescrip: "A visible bulge shifts along <pred>'s pelvis..." },
    { id: 9, graphNodeId: "9", type: "destination", destination: "Womb", mode: "Womb", digestionTimer: "120", x: 305, y: 380, protoConnections: [10], destinationDescrip: "You are wholly enveloped in a humid heat as you are deposited into a wet and slimy chamber. The air is filled with the scent of <pred>'s arousal and their heart can be heard beating just above.", examineMsgDescrip: "<pred>'s lower belly bulges warmly with life...", struggleInsideMsgDescrip: "Struggling seems to do little good, but you do feel the gentle rubbing of <pred>'s hand over your shape as they press the bulges you make back into their core.", struggleOutsideMsgDescrip: "<pred>'s distended belly seems to rock and sway on it's own, they coo softly and seem to rub over their middle affectionately.", digestionInsideMsgDescrip: "Your body seems to feel soggy and wet as the heat surrounding you grows more intense. The walls seem to flex down harder and harder until finally... splorsh! You succumb to <pred>'s arousal and are reduced to a pool of fem-cum.", digestionOutsideMsgDescrip: "<pred>'s middle suddenly compacts down noticeably and their face flushes red as they bite their lower lip. A muffled sloshing sound could be heard seemingly coming from their belly!", releaseMsgDescrip: "<pred>'s body convulses as they push you back out through their canal, birthing you back into freedom." },
    { id: 10, graphNodeId: "10", type: "exit", destination: "Slit", x: 445, y: 380, destinationDescrip: "You are birthed out through the slick slit...", examineMsgDescrip: "", struggleInsideMsgDescrip: "You press outward toward freedom...", struggleOutsideMsgDescrip: "<pred>'s slit widens as you push..." },
    { id: 11, graphNodeId: "11", type: "entrance", destination: "Cock", verb: "forces", x: 25, y: 520, protoConnections: [12], destinationDescrip: "You are forced into the tip of <pred>'s cock...", examineMsgDescrip: "<prey> is sliding inside the tip of <pred>'s cock...", struggleInsideMsgDescrip: "You squirm against the narrow opening...", struggleOutsideMsgDescrip: "<pred>'s cock twitches as <prey> slides in..." },
    { id: 12, graphNodeId: "12", type: "path", destination: "Shaft", x: 165, y: 520, protoConnections: [13], destinationDescrip: "The tight, throbbing shaft constricts around you...", examineMsgDescrip: "<prey> is sliding deeper into <pred>'s cock, making a visible bulge along it's length...", struggleInsideMsgDescrip: "The slick inner walls clamp tight...", struggleOutsideMsgDescrip: "A distinct bulge squirms along the underside of <pred>'s girth..." },
    { id: 13, graphNodeId: "13", type: "destination", destination: "Balls", mode: "Balls", digestionTimer: "120", x: 305, y: 520, protoConnections: [14], destinationDescrip: "You fall down into a thick, musky puddle of jizz that immediately starts coating your body as the wrinkly walls of <pred>'s scrotum tighten up to welcome you~", examineMsgDescrip: "A large bulge between <pred>'s thighs seems to shift and sway on it's own.", struggleInsideMsgDescrip: "The walls of your prison seem to give easily when you push out against them, but they always clench right back down the moment you relax...", struggleOutsideMsgDescrip: "A very clear imprint of someone's face bulges out from the side of <pred>'s nutsack.", digestionInsideMsgDescrip: "The walls around you suddenly cinch up tightly submerging your head completely in <pred>'s sperm before you finally melt, becoming one with the pool of seed you had been bathing in.", digestionOutsideMsgDescrip: "There are a few frantic garbled sounds seeming to come up from <pred>'s crotch before there was a sudden, thick sounding, GLORP and those frantic sounds were reduced to a soft sloshing.", releaseMsgDescrip: "With a powerful thrust, <pred> expels you from their sack, sending you sliding out into the world." },
    { id: 14, graphNodeId: "14", type: "exit", destination: "Cock", x: 445, y: 520, destinationDescrip: "You are ejaculated out from <pred>'s cock...", struggleInsideMsgDescrip: "You push outward down the shaft...", struggleOutsideMsgDescrip: "<pred>'s shaft throbs as you move..." }
];